<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Building design and energy efficiency</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="final_project_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_project_files/libs/quarto-html/quarto.js"></script>
<script src="final_project_files/libs/quarto-html/popper.min.js"></script>
<script src="final_project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_project_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Building design and energy efficiency</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Pochman, Spencer Wilson, Walter Vogelmann, Zach Perry </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<style type="text/css">
h1.title {
font-size: 40px;
text-align: center;
}
h4.author {
font-size: 40px;
text-align: center;
}
</style>
<div style="page-break-after: always;"></div>
<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>This study developed a linear regression model to predict the impact of various architectural design features on climate control energy efficiency. Key variables tested included volume to surface area ratio, floor plan area, area of external walls, number of stories, and area of windows, aiming to predict heating or cooling load in KWh per square meter. Significant predictors identified were area of external walls, number of stories, area of windows, and the interaction between number of stories and area of windows. External wall area showed the highest coefficient, indicating increased difficulty in heating and cooling control with a more robust exterior. Additionally, increases in area—whether through stories, window area, or their interaction—increased heating and cooling load, with a larger impact on heating load compared to cooling. Despite meeting assumptions of independent sampling, no influential points, and equal variance, the model struggled with normality issues in residuals, affecting precision and potentially reliability. Findings suggest that reducing external wall area, minimizing windows, and limiting the number of stories can decrease energy consumption for climate control. The models developed can aid in predicting energy consumption for architectural projects or for individuals considering energy efficiency in residences. Future research could explore additional variables and consider models like random forests to address normality issues.</p>
</section>
<section id="problem-and-motivation" class="level1">
<h1>1 Problem and Motivation</h1>
<p>This study was done to examine the effects of architectural design features on the energy efficiency of building design. Heating and cooling contribute to a significant portion of energy usage in many buildings around the world. By using sound architectural principles, we can reduce energy costs and carbon emissions. These data can help us to understand what design features are most connected with reduced energy usage. It’s important to focus conservation efforts on the vectors that matter most.</p>
<p>In our chosen study, researchers simulated the effects of several different factors that might affect energy usage when cooling or heating a building. In addition, they reported slightly different effects of these factors on the heating cost and cooling costs individually.</p>
<p>The following graph illustrates this idea. It compares the energy usage for heating and cooling:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Heat, <span class="at">y =</span> Cool, <span class="at">color =</span> twoStories)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1 Story"</span>, <span class="st">"2 Stories"</span>)) <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Energy usage of heating and cooling is correlated yet not equal"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Number of stories"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Energy usage in cooling (KWh/m2)"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Energy usage in heating (KWh/m2)"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We’ll compare and contrast the effects of different factors on heating and cooling; it’s interesting to note visually the relationship between heating costs and cooling costs. Rarely will a building be very efficient at heating but not at cooling or vice-versa. You can also see the effect of the number of stories a house has; many of the two story houses needed more energy for both heating and cooling.</p>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">1.1 Data Description</h2>
<p>This data was originally sampled from architectural simulation software (Ecotect) that simulates many things about architectural designs, including their energy efficiency and heating/cooling requirements. Each observation represents a different design for a building and its simulated heating and cooling load. Below is a table describing the different variables collected:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Feature</th>
<th style="text-align: right;">Range</th>
<th style="text-align: right;">Unit</th>
<th style="text-align: right;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">RelativeCompactness</td>
<td style="text-align: right;">0.68–0.98</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">The volume to surface ratio compared to the most compact shape with same volume</td>
</tr>
<tr class="even">
<td style="text-align: right;">SurfaceArea</td>
<td style="text-align: right;">514–808</td>
<td style="text-align: right;"><span class="math inline">\(m^2\)</span></td>
<td style="text-align: right;">The total area occupied by the floor plan of the building</td>
</tr>
<tr class="odd">
<td style="text-align: right;">WallArea</td>
<td style="text-align: right;">245–416</td>
<td style="text-align: right;"><span class="math inline">\(m^2\)</span></td>
<td style="text-align: right;">Total area of the exterior building wall including all openings</td>
</tr>
<tr class="even">
<td style="text-align: right;">RoofArea</td>
<td style="text-align: right;">110–220</td>
<td style="text-align: right;"><span class="math inline">\(m^2\)</span></td>
<td style="text-align: right;">the surface area of the roof</td>
</tr>
<tr class="odd">
<td style="text-align: right;">OverallHeight</td>
<td style="text-align: right;">3.5–7</td>
<td style="text-align: right;">m</td>
<td style="text-align: right;">Height from the lowest point of conditioned space to the highest point</td>
</tr>
<tr class="even">
<td style="text-align: right;">GlazingArea</td>
<td style="text-align: right;">0–0.4</td>
<td style="text-align: right;"><span class="math inline">\(m^2\)</span></td>
<td style="text-align: right;">The total area of the walls occupied by windows</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Output</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">HeatingLoad</td>
<td style="text-align: right;">6–43</td>
<td style="text-align: right;">KWh/<span class="math inline">\(m^2\)</span></td>
<td style="text-align: right;">Amount of heat added per square meter to maintain comfortable temperature</td>
</tr>
<tr class="odd">
<td style="text-align: right;">CoolingLoad</td>
<td style="text-align: right;">10–48</td>
<td style="text-align: right;">KWh/<span class="math inline">\(m^2\)</span></td>
<td style="text-align: right;">The amount of heat removed per square meter to maintain comfortable temperature</td>
</tr>
</tbody>
</table>
</section>
<section id="questions-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="questions-of-interest">1.2 Questions of Interest</h2>
<p>Do architectural factors such as the dimensions of the walls and roof, the size of windows, and overall compactness of a house have an effect on its energy efficiency when cooling?</p>
<p>Do these same factors have a different effect on the efficiency when warming the house?</p>
</section>
<section id="regression-methods" class="level2">
<h2 class="anchored" data-anchor-id="regression-methods">1.3 Regression Methods</h2>
<p>Our route to achieving a good model for the data was a long one. We needed to employ many different strategies to first pick the variables which we included, and then to apply transformations to those variables to meet the conditions for a linear model. Our variable selection code can be found in the appendix.</p>
<p>First in our assumptions is a linear relationship. The core premise of multiple linear regression is the existence of a linear relationship between the response and the explanatory variables, which was displayed in the scatterplot above.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Heat Linear Model</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>heat_trans_lm_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Heat) <span class="sc">~</span> <span class="fu">log</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                      GlazingA <span class="sc">+</span> twoStories<span class="sc">*</span>GlazingA, <span class="at">data =</span> energy)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(heat_trans_lm_small<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  heat_trans_lm_small$residuals
W = 0.96269, p-value = 4.415e-13</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cool Linear Model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>cool_trans_lm_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Cool) <span class="sc">~</span> <span class="fu">log</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                      GlazingA <span class="sc">+</span> twoStories<span class="sc">*</span>GlazingA, <span class="at">data =</span> energy) <span class="co"># best model so far</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(cool_trans_lm_small<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  cool_trans_lm_small$residuals
W = 0.97676, p-value = 1.063e-09</code></pre>
</div>
</div>
<p>Next, we need normality, which assumes that the residuals are normally distributed. For this, we performed many Wilk-Shapiro tests and this is where we hit a wall. Despite our best efforts, we could not get our data to be normal. We were able to minimize the break of this assumption as much as possible, but we finally concluded that this is just a weakness from the data. Here are our other plots for this assumption:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_trans_lm_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_trans_lm_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As the plots show, there is relatively normal distribution on the residuals, and this came after attempting many models to get the best fit for normality. This included the least deviation on the Q-Q plot and randomized scatting of the residuals across the fitted values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multicollinearity Plot</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>continuous <span class="ot">&lt;-</span> energy <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>twoStories, <span class="sc">-</span>RoofA, <span class="sc">-</span>SurfaceA)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(continuous), <span class="at">type =</span> <span class="st">'upper'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We also checked that there was no multicollinearity. This was shown in the above correlation plot. In a correlation matrices, the coefficients should ideally be below 0.80 which is the case aside from the correlation from heat and cool, which is a logical connection since they are opposites.</p>
<p>For the homoscedasticity assumption, the variance of error terms (residuals) should be consistent across all levels of the independent variables. A scatterplot of residuals versus predicted values should not display any discernible pattern, such as a cone-shaped distribution, which is not visible in the plots shown with the normality assumption.</p>
</section>
</section>
<section id="analyses-results-and-interpretation" class="level1">
<h1>2 Analyses, Results, and Interpretation</h1>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Heat Linear Model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(heat_trans_lm_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(Heat)
                     Df  Sum Sq Mean Sq  F value    Pr(&gt;F)    
log(WallA)            1  36.657  36.657 2490.427 &lt; 2.2e-16 ***
twoStories            1 111.032 111.032 7543.298 &lt; 2.2e-16 ***
GlazingA              1  15.047  15.047 1022.256 &lt; 2.2e-16 ***
twoStories:GlazingA   1   0.280   0.280   19.005 1.482e-05 ***
Residuals           763  11.231   0.015                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Heat Linear Model Anova Interpretation:</p>
<p>The ANOVA results for the heat linear model indicate significant effects of various architectural factors on heating energy efficiency. Specifically: - <strong>Wall Area (log(WallA)):</strong> There is a highly significant effect (p &lt; 0.001) of wall area on heating energy usage, with a large F-value of 2490.427. - <strong>Number of Stories (twoStories):</strong> Similarly, the number of stories in a building significantly impacts heating energy consumption (p &lt; 0.001), with a substantial F-value of 7543.298. - <strong>Glazing Area (GlazingA):</strong> Glazing area also shows a significant effect (p &lt; 0.001) on heating energy usage, with an F-value of 1022.256. - <strong>Interaction Effect (twoStories:GlazingA):</strong> The interaction between number of stories and glazing area is also significant (p = 1.482e-05), suggesting a combined influence on heating energy efficiency.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cool Linear Model</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(cool_trans_lm_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(Cool)
                     Df Sum Sq Mean Sq   F value Pr(&gt;F)    
log(WallA)            1 21.971  21.971 1716.9988 &lt;2e-16 ***
twoStories            1 80.944  80.944 6325.5976 &lt;2e-16 ***
GlazingA              1  5.605   5.605  437.9870 &lt;2e-16 ***
twoStories:GlazingA   1  0.021   0.021    1.6203 0.2034    
Residuals           763  9.764   0.013                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Cool Linear Model Anova Interpretation:</p>
<p>The ANOVA results for the cool linear model also reveals significant effects of architectural factors, but for cooling energy efficiency: - <strong>Wall Area (log(WallA)):</strong> Wall area significantly affects cooling energy usage (p &lt; 0.001), with a high F-value of 1716.9988. - <strong>Number of Stories (twoStories):</strong> Similar to heating, the number of stories has a significant impact on cooling energy consumption (p &lt; 0.001), with an F-value of 6325.5976. - <strong>Glazing Area (GlazingA):</strong> Glazing area also shows a significant effect (p &lt; 0.001) on cooling energy usage, with an F-value of 437.9870. - <strong>Interaction Effect (twoStories:GlazingA):</strong> The interaction between number of stories and glazing area, however, is not significant (p = 0.2034), indicating no combined influence on cooling energy efficiency, which is an interesting difference from the heat model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(heat_trans_lm_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %     97.5 %
(Intercept)          -2.4097643 -1.6465672
log(WallA)            0.6886807  0.8219476
twoStories1           0.8273967  0.8977901
GlazingA              1.1034303  1.2860117
twoStories1:GlazingA -0.4158140 -0.1576049</code></pre>
</div>
</div>
<p>Confidence Intervals Interpretation for Heat Linear Model:</p>
<p>Intercept: The 95% confidence interval for the intercept ranges from approximately -2.41 to -1.65. This suggests that, holding all other variables constant, the expected heating load varies between -2.41 and -1.65 KWh/<span class="math inline">\(m^2\)</span>. Wall Area (log(WallA)): The 95% confidence interval for the coefficient of log(WallA) ranges from approximately 0.69 to 0.82. It implies that for each one-unit increase in wall area, the log heating load is expected to increase between 1.991087 and 2.274926 KWh/<span class="math inline">\(m^2\)</span>, holding all other variables constant. Number of Stories (twoStories1): The 95% confidence interval for the coefficient of the number of stories (twoStories1) ranges from approximately 0.83 to 0.90. It suggests that, compared to one-story buildings, two-story buildings are expected to have a log heating load between 0.83 and 0.90 KWh/<span class="math inline">\(m^2\)</span> higher, holding all other variables constant. Glazing Area (GlazingA): The 95% confidence interval for the coefficient of GlazingA ranges from approximately 1.10 to 1.29. It implies that for each one <span class="math inline">\(m^2\)</span> increase in glazing area, the log heating load is expected to increase between 1.10 and 1.29 KWh/<span class="math inline">\(m^2\)</span>, holding all other variables constant. Interaction Effect (twoStories1:GlazingA): The 95% confidence interval for the coefficient of the interaction term ranges from approximately -0.42 to -0.16. It suggests that the effect of the interaction between number of stories and glazing area on the log heating load is expected to decrease between -0.42 and -0.16 KWh/<span class="math inline">\(m^2\)</span>, holding all other variables constant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(cool_trans_lm_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %     97.5 %
(Intercept)          -0.6977434 0.01385527
log(WallA)            0.4538063 0.57806325
twoStories1           0.6646053 0.73023953
GlazingA              0.5955657 0.76580313
twoStories1:GlazingA -0.1984302 0.04232186</code></pre>
</div>
</div>
<p>Confidence Intervals Interpretation for Cool Linear Model:</p>
<p>Intercept: The 95% confidence interval for the intercept ranges from approximately -0.70 to 0.01. This suggests that, holding all other variables constant, the expected log cooling load varies between -0.70 and 0.01 KWh/<span class="math inline">\(m^2\)</span>. Wall Area (log(WallA)): The 95% confidence interval for the coefficient of log(WallA) ranges from approximately 0.45 to 0.58. It implies that for each one-unit increase in the log of wall area, the log cooling load is expected to increase between 0.45 and 0.58 KWh/<span class="math inline">\(m^2\)</span>, holding all other variables constant. Number of Stories (twoStories1): The 95% confidence interval for the coefficient of the number of stories (twoStories1) ranges from approximately 0.66 to 0.73. It suggests that, compared to one-story buildings, two-story buildings are expected to have a log cooling load between 0.66 and 0.73 KWh/<span class="math inline">\(m^2\)</span> higher, holding all other variables constant. Glazing Area (GlazingA): The 95% confidence interval for the coefficient of GlazingA ranges from approximately 0.60 to 0.77. It implies that for each one <span class="math inline">\(m^2\)</span> increase in glazing area, the log cooling load is expected to increase between 0.60 and 0.77 KWh/<span class="math inline">\(m^2\)</span>, holding all other variables constant. Interaction Effect (twoStories1:GlazingA): The 95% confidence interval for the coefficient of the interaction term ranges from approximately -0.20 to 0.04. It suggests that the effect of the interaction between number of stories and glazing area on the log cooling load is not statistically significant, as the interval includes zero.</p>
<p>INTERPRET PREDICTION INTERVAL HERE***</p>
</section>
<section id="conclusions" class="level1">
<h1>3 Conclusions</h1>
<p>This study aimed to create a linear regression model to predict how various architecture design features impact climate control energy efficiency. The main variables we were interested in testing include volume to surface area ratio, the floor plan area, the area of external walls, number of stories, and the area of windows. Using these predictors, we attempted to predict the amount of heat added or removed in KWh per square meter (heating or cooling load).</p>
<p>We found the area of external walls, the number of stories, the area of windows, and the combination effect of the number of stories and the area of windows to be significant predictors of energy efficiency. The predictor with the highest coefficient was external wall area, suggesting that a more robust exterior to architecture increases the heating and cooling load more than any other variable, making it harder to add or remove heat when more window area is present. As stated, this trend was relevant for both heating and cool load, although it can be important to note that a larger external wall area did place a higher load on heating as compared to cooling. Similarly to external wall area, an increase in area, whether it be area increased by stories, area of windows, or an interaction of the two predictors also increases heating and cooling load.</p>
<p>Our models aimed to use these significant variables to make models that can predict heating and cooling load. When testing model assumptions, we ran into some issues with normality. Other assumptions such as independent sampling, no influential points, and equal variance were met, however our model was unable to explain variance in the tail even after multiple attempts at transforming the data using logarithmic and exponential transformations. This caused normality issues in the residuals which were noted before moving on. The largest impact of non-normal residuals is increased variance in our results. We were still able to identify trends, but our coefficients had larger than optimal margins of error which decreased our model’s precision and potentially its reliability.</p>
<p>Our findings have important implications for real world architextural design practice. If heating and cooling load is a concern, whether for financial or environmental reasons, houses should decrease external wall area where possible. Removing windows and limiting the number of stories in a building also decrease energy consumption when under heating and cooling loads. Our models can assist in predicting climate control energy consumption for potential architectural projects or for buyers weighing the cost of energy efficiency for a new residence.</p>
<p>Future research could aim to add more variables to the models or to create a random forest model, which would not be as restrained by normality issues. Placement of air conditioning or heating units within a home, types of units, and average room size are other factors that have the potential to impact heating and cooling load. Future studies could dive into more nuanced effects of those factors and their interactions with our included predictors.</p>
</section>
<section id="contributions" class="level1">
<h1>4 Contributions</h1>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">APPENDIX</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bestglm)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>energy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"ENB2012_data.csv"</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>energy <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(energy)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># change col names</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(energy) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'Compact'</span>, <span class="st">'SurfaceA'</span>, <span class="st">'WallA'</span>, <span class="st">'RoofA'</span>, <span class="st">'twoStories'</span>, <span class="st">'Orient'</span>, <span class="st">'GlazingA'</span>, <span class="st">'GlazingADist'</span>, <span class="st">'Heat'</span>, <span class="st">'Cool'</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="co"># remove data we are not using</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>energy<span class="sc">$</span>Orient <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>energy<span class="sc">$</span>GlazingADist <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="co"># change building height to categorical</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>energy<span class="sc">$</span>twoStories <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(energy<span class="sc">$</span>twoStories <span class="sc">==</span> <span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>energy<span class="sc">$</span>twoStories <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(energy<span class="sc">$</span>twoStories)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(energy)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a><span class="co"># some visualization of the data</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Heat, <span class="at">y =</span> Cool, <span class="at">color =</span> twoStories))</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> twoStories, <span class="at">y =</span> Heat))</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> Compact, <span class="at">y =</span> Heat, <span class="at">color =</span> twoStories), <span class="at">position =</span> <span class="st">'jitter'</span>)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> SurfaceA, <span class="at">y =</span> Heat, <span class="at">color =</span> twoStories), <span class="at">position =</span> <span class="st">'jitter'</span>)</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> WallA, <span class="at">y =</span> Heat, <span class="at">color =</span> twoStories), <span class="at">position =</span> <span class="st">'jitter'</span>)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> RoofA, <span class="at">y =</span> Heat, <span class="at">color =</span> twoStories), <span class="at">position =</span> <span class="st">'jitter'</span>)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> energy) <span class="sc">+</span></span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> GlazingA, <span class="at">y =</span> Heat, <span class="at">color =</span> twoStories), <span class="at">position =</span> <span class="st">'jitter'</span>)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a><span class="co"># it looks like there will be some interaction terms with number of stories and </span></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># some of the other variables. Heating and cooling also look to be very </span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>    <span class="co"># closely correlated</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a><span class="co"># check for multicollinearity between continuous variables</span></span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>continuous <span class="ot">&lt;-</span> energy <span class="sc">%&gt;%</span></span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>twoStories, <span class="sc">-</span>RoofA, <span class="sc">-</span>SurfaceA)</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(continuous), <span class="at">type =</span> <span class="st">'upper'</span>)</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(continuous),<span class="dv">2</span>)</span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a><span class="co"># it looks like there is some multicollinearity between the variables</span></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a><span class="co"># create a full linear model for both heating and cooling</span></span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>heating_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Heat <span class="sc">~</span> Compact <span class="sc">+</span> SurfaceA <span class="sc">+</span> WallA <span class="sc">+</span> RoofA <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>                   GlazingA, <span class="at">data =</span> energy)</span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>cooling_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cool <span class="sc">~</span> Compact <span class="sc">+</span> SurfaceA <span class="sc">+</span> WallA <span class="sc">+</span> RoofA <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>                   GlazingA, <span class="at">data =</span> energy)</span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heating_lm)</span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cooling_lm)</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(heating_lm)</span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(cooling_lm)</span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a><span class="co">#vif(heating_lm)</span></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a><span class="co"># both models removed Roof Area, i think because it is perfectly multicollinear</span></span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a><span class="co"># with number of stories</span></span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a><span class="co"># check diagnostics on base models</span></span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heating_lm)</span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heating_lm, <span class="at">which =</span> <span class="dv">4</span>)</span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cooling_lm)</span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cooling_lm, <span class="at">which =</span> <span class="dv">4</span>)</span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(heating_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(heating_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(heating_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(cooling_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-77"><a href="#cb17-77" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cooling_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-78"><a href="#cb17-78" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(cooling_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a><span class="co"># neither model has normally distributed errors and there could some problems</span></span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a><span class="co"># equality of variance</span></span>
<span id="cb17-81"><a href="#cb17-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-82"><a href="#cb17-82" aria-hidden="true" tabindex="-1"></a><span class="co"># Interactions</span></span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Heat <span class="sc">~</span> Compact<span class="sc">*</span>twoStories <span class="sc">+</span> SurfaceA<span class="sc">*</span>twoStories <span class="sc">+</span> WallA<span class="sc">*</span>twoStories</span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a>             <span class="sc">+</span> GlazingA, <span class="at">data =</span> energy)</span>
<span id="cb17-85"><a href="#cb17-85" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova)</span>
<span id="cb17-86"><a href="#cb17-86" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor =</span> energy<span class="sc">$</span>Compact, </span>
<span id="cb17-87"><a href="#cb17-87" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace.factor =</span> energy<span class="sc">$</span>twoStories, </span>
<span id="cb17-88"><a href="#cb17-88" aria-hidden="true" tabindex="-1"></a>                 <span class="at">response =</span> energy<span class="sc">$</span>Heat)</span>
<span id="cb17-89"><a href="#cb17-89" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor =</span> energy<span class="sc">$</span>SurfaceA, </span>
<span id="cb17-90"><a href="#cb17-90" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace.factor =</span> energy<span class="sc">$</span>twoStories, </span>
<span id="cb17-91"><a href="#cb17-91" aria-hidden="true" tabindex="-1"></a>                 <span class="at">response =</span> energy<span class="sc">$</span>Heat)</span>
<span id="cb17-92"><a href="#cb17-92" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor =</span> energy<span class="sc">$</span>WallA, </span>
<span id="cb17-93"><a href="#cb17-93" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace.factor =</span> energy<span class="sc">$</span>twoStories, </span>
<span id="cb17-94"><a href="#cb17-94" aria-hidden="true" tabindex="-1"></a>                 <span class="at">response =</span> energy<span class="sc">$</span>Heat)</span>
<span id="cb17-95"><a href="#cb17-95" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor =</span> energy<span class="sc">$</span>RoofA, </span>
<span id="cb17-96"><a href="#cb17-96" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace.factor =</span> energy<span class="sc">$</span>twoStories, </span>
<span id="cb17-97"><a href="#cb17-97" aria-hidden="true" tabindex="-1"></a>                 <span class="at">response =</span> energy<span class="sc">$</span>Heat)</span>
<span id="cb17-98"><a href="#cb17-98" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor =</span> energy<span class="sc">$</span>GlazingA, </span>
<span id="cb17-99"><a href="#cb17-99" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace.factor =</span> energy<span class="sc">$</span>twoStories, </span>
<span id="cb17-100"><a href="#cb17-100" aria-hidden="true" tabindex="-1"></a>                 <span class="at">response =</span> energy<span class="sc">$</span>Heat)</span>
<span id="cb17-101"><a href="#cb17-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-102"><a href="#cb17-102" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(<span class="at">x.factor =</span> energy<span class="sc">$</span>GlazingA, </span>
<span id="cb17-103"><a href="#cb17-103" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trace.factor =</span> energy<span class="sc">$</span>Compact, </span>
<span id="cb17-104"><a href="#cb17-104" aria-hidden="true" tabindex="-1"></a>                 <span class="at">response =</span> energy<span class="sc">$</span>Heat)</span>
<span id="cb17-105"><a href="#cb17-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-106"><a href="#cb17-106" aria-hidden="true" tabindex="-1"></a><span class="co"># looks like number of stories has an interaction with  compact, surface area,</span></span>
<span id="cb17-107"><a href="#cb17-107" aria-hidden="true" tabindex="-1"></a><span class="co"># and wall area</span></span>
<span id="cb17-108"><a href="#cb17-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-109"><a href="#cb17-109" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a new model with the interaction terms</span></span>
<span id="cb17-110"><a href="#cb17-110" aria-hidden="true" tabindex="-1"></a>heat_interax_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Heat <span class="sc">~</span> Compact <span class="sc">+</span> SurfaceA <span class="sc">+</span> WallA <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-111"><a href="#cb17-111" aria-hidden="true" tabindex="-1"></a>                        GlazingA <span class="sc">+</span> WallA<span class="sc">*</span>twoStories <span class="sc">+</span> Compact<span class="sc">*</span>twoStories <span class="sc">+</span> </span>
<span id="cb17-112"><a href="#cb17-112" aria-hidden="true" tabindex="-1"></a>                        SurfaceA<span class="sc">*</span>twoStories, <span class="at">data =</span> energy)</span>
<span id="cb17-113"><a href="#cb17-113" aria-hidden="true" tabindex="-1"></a>cool_interax_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cool <span class="sc">~</span> Compact <span class="sc">+</span> SurfaceA <span class="sc">+</span> WallA <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-114"><a href="#cb17-114" aria-hidden="true" tabindex="-1"></a>                        GlazingA <span class="sc">+</span> WallA<span class="sc">*</span>twoStories <span class="sc">+</span> Compact<span class="sc">*</span>twoStories <span class="sc">+</span> </span>
<span id="cb17-115"><a href="#cb17-115" aria-hidden="true" tabindex="-1"></a>                        SurfaceA<span class="sc">*</span>twoStories, <span class="at">data =</span> energy)</span>
<span id="cb17-116"><a href="#cb17-116" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heat_interax_lm)</span>
<span id="cb17-117"><a href="#cb17-117" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cool_interax_lm)</span>
<span id="cb17-118"><a href="#cb17-118" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_interax_lm)</span>
<span id="cb17-119"><a href="#cb17-119" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_interax_lm)</span>
<span id="cb17-120"><a href="#cb17-120" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(heat_interax_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-121"><a href="#cb17-121" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(cool_interax_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-122"><a href="#cb17-122" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(heat_interax_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-123"><a href="#cb17-123" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cool_interax_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-124"><a href="#cb17-124" aria-hidden="true" tabindex="-1"></a><span class="co"># a model with all the interactions still has the same problems</span></span>
<span id="cb17-125"><a href="#cb17-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-126"><a href="#cb17-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-127"><a href="#cb17-127" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable Selection/Shrinkage</span></span>
<span id="cb17-128"><a href="#cb17-128" aria-hidden="true" tabindex="-1"></a>heat <span class="ot">&lt;-</span> energy <span class="sc">%&gt;%</span></span>
<span id="cb17-129"><a href="#cb17-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Compact, SurfaceA, WallA, RoofA, twoStories, GlazingA, Heat)</span>
<span id="cb17-130"><a href="#cb17-130" aria-hidden="true" tabindex="-1"></a>cool <span class="ot">&lt;-</span> energy <span class="sc">%&gt;%</span></span>
<span id="cb17-131"><a href="#cb17-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Compact, SurfaceA, WallA, RoofA, twoStories, GlazingA, Cool)</span>
<span id="cb17-132"><a href="#cb17-132" aria-hidden="true" tabindex="-1"></a>heat <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(heat)</span>
<span id="cb17-133"><a href="#cb17-133" aria-hidden="true" tabindex="-1"></a>cool <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(cool)</span>
<span id="cb17-134"><a href="#cb17-134" aria-hidden="true" tabindex="-1"></a>heat_x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(heat[, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]) </span>
<span id="cb17-135"><a href="#cb17-135" aria-hidden="true" tabindex="-1"></a>heat_y <span class="ot">&lt;-</span> heat[, <span class="dv">7</span>]</span>
<span id="cb17-136"><a href="#cb17-136" aria-hidden="true" tabindex="-1"></a>cool_x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(cool[, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]) </span>
<span id="cb17-137"><a href="#cb17-137" aria-hidden="true" tabindex="-1"></a>cool_y <span class="ot">&lt;-</span> cool[, <span class="dv">7</span>]</span>
<span id="cb17-138"><a href="#cb17-138" aria-hidden="true" tabindex="-1"></a><span class="do">## Ridge</span></span>
<span id="cb17-139"><a href="#cb17-139" aria-hidden="true" tabindex="-1"></a>heat_ridge_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> heat_x,</span>
<span id="cb17-140"><a href="#cb17-140" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> heat_y, </span>
<span id="cb17-141"><a href="#cb17-141" aria-hidden="true" tabindex="-1"></a>                          <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb17-142"><a href="#cb17-142" aria-hidden="true" tabindex="-1"></a>                          <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb17-143"><a href="#cb17-143" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_ridge_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-144"><a href="#cb17-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-145"><a href="#cb17-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-146"><a href="#cb17-146" aria-hidden="true" tabindex="-1"></a>heat_ridge_cv<span class="sc">$</span>lambda<span class="fl">.1</span>se</span>
<span id="cb17-147"><a href="#cb17-147" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(heat_ridge_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span>
<span id="cb17-148"><a href="#cb17-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-149"><a href="#cb17-149" aria-hidden="true" tabindex="-1"></a>cool_ridge_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> cool_x,</span>
<span id="cb17-150"><a href="#cb17-150" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> cool_y, </span>
<span id="cb17-151"><a href="#cb17-151" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb17-152"><a href="#cb17-152" aria-hidden="true" tabindex="-1"></a>                           <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb17-153"><a href="#cb17-153" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_ridge_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-154"><a href="#cb17-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-155"><a href="#cb17-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-156"><a href="#cb17-156" aria-hidden="true" tabindex="-1"></a>cool_ridge_cv<span class="sc">$</span>lambda<span class="fl">.1</span>se</span>
<span id="cb17-157"><a href="#cb17-157" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(cool_ridge_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span>
<span id="cb17-158"><a href="#cb17-158" aria-hidden="true" tabindex="-1"></a><span class="do">## LASSO</span></span>
<span id="cb17-159"><a href="#cb17-159" aria-hidden="true" tabindex="-1"></a>heat_lasso_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> heat_x,</span>
<span id="cb17-160"><a href="#cb17-160" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> heat_y, </span>
<span id="cb17-161"><a href="#cb17-161" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb17-162"><a href="#cb17-162" aria-hidden="true" tabindex="-1"></a>                           <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb17-163"><a href="#cb17-163" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_lasso_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-164"><a href="#cb17-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-165"><a href="#cb17-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-166"><a href="#cb17-166" aria-hidden="true" tabindex="-1"></a>heat_lasso_cv<span class="sc">$</span>lambda<span class="fl">.1</span>se</span>
<span id="cb17-167"><a href="#cb17-167" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(heat_lasso_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span>
<span id="cb17-168"><a href="#cb17-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-169"><a href="#cb17-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-170"><a href="#cb17-170" aria-hidden="true" tabindex="-1"></a>cool_lasso_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> cool_x,</span>
<span id="cb17-171"><a href="#cb17-171" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> cool_y, </span>
<span id="cb17-172"><a href="#cb17-172" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb17-173"><a href="#cb17-173" aria-hidden="true" tabindex="-1"></a>                           <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb17-174"><a href="#cb17-174" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_lasso_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-175"><a href="#cb17-175" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-176"><a href="#cb17-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-177"><a href="#cb17-177" aria-hidden="true" tabindex="-1"></a>cool_lasso_cv<span class="sc">$</span>lambda<span class="fl">.1</span>se</span>
<span id="cb17-178"><a href="#cb17-178" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(cool_lasso_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span>
<span id="cb17-179"><a href="#cb17-179" aria-hidden="true" tabindex="-1"></a><span class="do">## Elastic Net</span></span>
<span id="cb17-180"><a href="#cb17-180" aria-hidden="true" tabindex="-1"></a>heat_net_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> heat_x,</span>
<span id="cb17-181"><a href="#cb17-181" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> heat_y, </span>
<span id="cb17-182"><a href="#cb17-182" aria-hidden="true" tabindex="-1"></a>                           <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb17-183"><a href="#cb17-183" aria-hidden="true" tabindex="-1"></a>                           <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb17-184"><a href="#cb17-184" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_net_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-185"><a href="#cb17-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-186"><a href="#cb17-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-187"><a href="#cb17-187" aria-hidden="true" tabindex="-1"></a>heat_net_cv<span class="sc">$</span>lambda<span class="fl">.1</span>se</span>
<span id="cb17-188"><a href="#cb17-188" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(heat_net_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span>
<span id="cb17-189"><a href="#cb17-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-190"><a href="#cb17-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-191"><a href="#cb17-191" aria-hidden="true" tabindex="-1"></a>cool_net_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> cool_x,</span>
<span id="cb17-192"><a href="#cb17-192" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y =</span> cool_y, </span>
<span id="cb17-193"><a href="#cb17-193" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type.measure =</span> <span class="st">"mse"</span>, </span>
<span id="cb17-194"><a href="#cb17-194" aria-hidden="true" tabindex="-1"></a>                         <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb17-195"><a href="#cb17-195" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_net_cv, <span class="at">label =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-196"><a href="#cb17-196" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-197"><a href="#cb17-197" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-198"><a href="#cb17-198" aria-hidden="true" tabindex="-1"></a>cool_net_cv<span class="sc">$</span>lambda<span class="fl">.1</span>se</span>
<span id="cb17-199"><a href="#cb17-199" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(cool_net_cv, <span class="at">s =</span> <span class="st">"lambda.1se"</span>)</span>
<span id="cb17-200"><a href="#cb17-200" aria-hidden="true" tabindex="-1"></a><span class="do">## Forward</span></span>
<span id="cb17-201"><a href="#cb17-201" aria-hidden="true" tabindex="-1"></a>base_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Heat <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> heat) </span>
<span id="cb17-202"><a href="#cb17-202" aria-hidden="true" tabindex="-1"></a>full_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Heat <span class="sc">~</span> ., <span class="at">data =</span> heat) </span>
<span id="cb17-203"><a href="#cb17-203" aria-hidden="true" tabindex="-1"></a>base_mod_cool <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cool <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> cool) </span>
<span id="cb17-204"><a href="#cb17-204" aria-hidden="true" tabindex="-1"></a>full_mod_cool <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cool <span class="sc">~</span> ., <span class="at">data =</span> cool)</span>
<span id="cb17-205"><a href="#cb17-205" aria-hidden="true" tabindex="-1"></a>forw_BIC <span class="ot">&lt;-</span> <span class="fu">step</span>(base_mod,</span>
<span id="cb17-206"><a href="#cb17-206" aria-hidden="true" tabindex="-1"></a>                 <span class="at">direction =</span> <span class="st">"forward"</span>, </span>
<span id="cb17-207"><a href="#cb17-207" aria-hidden="true" tabindex="-1"></a>                 <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod, <span class="at">upper=</span> full_mod),</span>
<span id="cb17-208"><a href="#cb17-208" aria-hidden="true" tabindex="-1"></a>                 <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(heat)))</span>
<span id="cb17-209"><a href="#cb17-209" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(forw_BIC)</span>
<span id="cb17-210"><a href="#cb17-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-211"><a href="#cb17-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-212"><a href="#cb17-212" aria-hidden="true" tabindex="-1"></a>forw_BIC_cool <span class="ot">&lt;-</span> <span class="fu">step</span>(base_mod_cool,</span>
<span id="cb17-213"><a href="#cb17-213" aria-hidden="true" tabindex="-1"></a>                 <span class="at">direction =</span> <span class="st">"forward"</span>, </span>
<span id="cb17-214"><a href="#cb17-214" aria-hidden="true" tabindex="-1"></a>                 <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod_cool, <span class="at">upper=</span> full_mod_cool),</span>
<span id="cb17-215"><a href="#cb17-215" aria-hidden="true" tabindex="-1"></a>                 <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(cool)))</span>
<span id="cb17-216"><a href="#cb17-216" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(forw_BIC_cool)</span>
<span id="cb17-217"><a href="#cb17-217" aria-hidden="true" tabindex="-1"></a><span class="do">## Backward</span></span>
<span id="cb17-218"><a href="#cb17-218" aria-hidden="true" tabindex="-1"></a>back_BIC <span class="ot">&lt;-</span> <span class="fu">step</span>(full_mod,</span>
<span id="cb17-219"><a href="#cb17-219" aria-hidden="true" tabindex="-1"></a>                 <span class="at">direction =</span> <span class="st">"backward"</span>, </span>
<span id="cb17-220"><a href="#cb17-220" aria-hidden="true" tabindex="-1"></a>                 <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod, <span class="at">upper=</span> full_mod),</span>
<span id="cb17-221"><a href="#cb17-221" aria-hidden="true" tabindex="-1"></a>                 <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(heat)))</span>
<span id="cb17-222"><a href="#cb17-222" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(back_BIC)</span>
<span id="cb17-223"><a href="#cb17-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-224"><a href="#cb17-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-225"><a href="#cb17-225" aria-hidden="true" tabindex="-1"></a>back_BIC_cool <span class="ot">&lt;-</span> <span class="fu">step</span>(full_mod_cool,</span>
<span id="cb17-226"><a href="#cb17-226" aria-hidden="true" tabindex="-1"></a>                 <span class="at">direction =</span> <span class="st">"backward"</span>, </span>
<span id="cb17-227"><a href="#cb17-227" aria-hidden="true" tabindex="-1"></a>                 <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod_cool, <span class="at">upper=</span> full_mod_cool),</span>
<span id="cb17-228"><a href="#cb17-228" aria-hidden="true" tabindex="-1"></a>                 <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(cool)))</span>
<span id="cb17-229"><a href="#cb17-229" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(back_BIC_cool)</span>
<span id="cb17-230"><a href="#cb17-230" aria-hidden="true" tabindex="-1"></a><span class="do">## Sequential</span></span>
<span id="cb17-231"><a href="#cb17-231" aria-hidden="true" tabindex="-1"></a>full_seq_BIC <span class="ot">&lt;-</span> <span class="fu">step</span>(full_mod,</span>
<span id="cb17-232"><a href="#cb17-232" aria-hidden="true" tabindex="-1"></a>                     <span class="at">direction =</span> <span class="st">"both"</span>, </span>
<span id="cb17-233"><a href="#cb17-233" aria-hidden="true" tabindex="-1"></a>                     <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod, <span class="at">upper=</span> full_mod),</span>
<span id="cb17-234"><a href="#cb17-234" aria-hidden="true" tabindex="-1"></a>                     <span class="at">k=</span><span class="fu">log</span>(<span class="fu">nrow</span>(heat)))</span>
<span id="cb17-235"><a href="#cb17-235" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_seq_BIC)</span>
<span id="cb17-236"><a href="#cb17-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-237"><a href="#cb17-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-238"><a href="#cb17-238" aria-hidden="true" tabindex="-1"></a>full_seq_BIC_cool <span class="ot">&lt;-</span> <span class="fu">step</span>(full_mod_cool,</span>
<span id="cb17-239"><a href="#cb17-239" aria-hidden="true" tabindex="-1"></a>                     <span class="at">direction =</span> <span class="st">"both"</span>, </span>
<span id="cb17-240"><a href="#cb17-240" aria-hidden="true" tabindex="-1"></a>                     <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span> base_mod_cool, <span class="at">upper=</span> full_mod_cool),</span>
<span id="cb17-241"><a href="#cb17-241" aria-hidden="true" tabindex="-1"></a>                     <span class="at">k=</span><span class="fu">log</span>(<span class="fu">nrow</span>(cool)))</span>
<span id="cb17-242"><a href="#cb17-242" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_seq_BIC_cool)</span>
<span id="cb17-243"><a href="#cb17-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-244"><a href="#cb17-244" aria-hidden="true" tabindex="-1"></a><span class="co"># all the models for both explanatory variables agree to remove roof area and </span></span>
<span id="cb17-245"><a href="#cb17-245" aria-hidden="true" tabindex="-1"></a>    <span class="co"># keep compact, wall area, stories, and glazing area. LASSO and Net say</span></span>
<span id="cb17-246"><a href="#cb17-246" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove surface area, forward and backward say keep it</span></span>
<span id="cb17-247"><a href="#cb17-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-248"><a href="#cb17-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-249"><a href="#cb17-249" aria-hidden="true" tabindex="-1"></a><span class="fu">invTranPlot</span>(<span class="fu">log</span>(Heat) <span class="sc">~</span> Compact , <span class="at">data =</span> heat, <span class="at">lambda =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-250"><a href="#cb17-250" aria-hidden="true" tabindex="-1"></a><span class="fu">invTranPlot</span>(<span class="fu">log</span>(Heat) <span class="sc">~</span> WallA , <span class="at">data =</span> heat, <span class="at">lambda =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-251"><a href="#cb17-251" aria-hidden="true" tabindex="-1"></a><span class="fu">invTranPlot</span>(<span class="fu">log</span>(Heat) <span class="sc">~</span> GlazingA, <span class="at">data =</span> heat, <span class="at">lambda =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-252"><a href="#cb17-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-253"><a href="#cb17-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-254"><a href="#cb17-254" aria-hidden="true" tabindex="-1"></a><span class="fu">invTranPlot</span>(<span class="fu">log</span>(Cool) <span class="sc">~</span> Compact , <span class="at">data =</span> cool, <span class="at">lambda =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-255"><a href="#cb17-255" aria-hidden="true" tabindex="-1"></a><span class="fu">invTranPlot</span>(<span class="fu">log</span>(Cool) <span class="sc">~</span> WallA , <span class="at">data =</span> cool, <span class="at">lambda =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-256"><a href="#cb17-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-257"><a href="#cb17-257" aria-hidden="true" tabindex="-1"></a>bc <span class="ot">=</span> <span class="fu">boxCox</span>(heating_lm)</span>
<span id="cb17-258"><a href="#cb17-258" aria-hidden="true" tabindex="-1"></a>lambda.opt <span class="ot">=</span> bc<span class="sc">$</span>x[<span class="fu">which.max</span>(bc<span class="sc">$</span>y)]</span>
<span id="cb17-259"><a href="#cb17-259" aria-hidden="true" tabindex="-1"></a>lambda.opt</span>
<span id="cb17-260"><a href="#cb17-260" aria-hidden="true" tabindex="-1"></a>heat_trans_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Heat) <span class="sc">~</span> <span class="dv">1</span><span class="sc">/</span>(WallA<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-261"><a href="#cb17-261" aria-hidden="true" tabindex="-1"></a>                      GlazingA <span class="sc">+</span> twoStories<span class="sc">*</span>GlazingA, <span class="at">data =</span> heat)</span>
<span id="cb17-262"><a href="#cb17-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-263"><a href="#cb17-263" aria-hidden="true" tabindex="-1"></a>cool_trans_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Cool) <span class="sc">~</span> <span class="fu">log</span>(Compact) <span class="sc">+</span> <span class="fu">log</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-264"><a href="#cb17-264" aria-hidden="true" tabindex="-1"></a>                      GlazingA <span class="sc">+</span> twoStories<span class="sc">*</span>GlazingA, <span class="at">data =</span> cool)</span>
<span id="cb17-265"><a href="#cb17-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-266"><a href="#cb17-266" aria-hidden="true" tabindex="-1"></a><span class="do">#######</span></span>
<span id="cb17-267"><a href="#cb17-267" aria-hidden="true" tabindex="-1"></a><span class="co"># MAIN MODELS</span></span>
<span id="cb17-268"><a href="#cb17-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-269"><a href="#cb17-269" aria-hidden="true" tabindex="-1"></a><span class="co"># Heat Linear Model</span></span>
<span id="cb17-270"><a href="#cb17-270" aria-hidden="true" tabindex="-1"></a>heat_trans_lm_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Heat) <span class="sc">~</span> <span class="fu">log</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-271"><a href="#cb17-271" aria-hidden="true" tabindex="-1"></a>                      GlazingA <span class="sc">+</span> twoStories<span class="sc">*</span>GlazingA, <span class="at">data =</span> heat)</span>
<span id="cb17-272"><a href="#cb17-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-273"><a href="#cb17-273" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_trans_lm_small)</span>
<span id="cb17-274"><a href="#cb17-274" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(heat_trans_lm_small)</span>
<span id="cb17-275"><a href="#cb17-275" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(heat_trans_lm_small)</span>
<span id="cb17-276"><a href="#cb17-276" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(heat_trans_lm_small<span class="sc">$</span>residuals)</span>
<span id="cb17-277"><a href="#cb17-277" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heat_trans_lm_small)</span>
<span id="cb17-278"><a href="#cb17-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-279"><a href="#cb17-279" aria-hidden="true" tabindex="-1"></a><span class="co"># Cool Linear Model</span></span>
<span id="cb17-280"><a href="#cb17-280" aria-hidden="true" tabindex="-1"></a>cool_trans_lm_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Cool) <span class="sc">~</span> <span class="fu">log</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> </span>
<span id="cb17-281"><a href="#cb17-281" aria-hidden="true" tabindex="-1"></a>                      GlazingA <span class="sc">+</span> twoStories<span class="sc">*</span>GlazingA, <span class="at">data =</span> cool)</span>
<span id="cb17-282"><a href="#cb17-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-283"><a href="#cb17-283" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_trans_lm_small)</span>
<span id="cb17-284"><a href="#cb17-284" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(cool_trans_lm_small)</span>
<span id="cb17-285"><a href="#cb17-285" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(cool_trans_lm_small)</span>
<span id="cb17-286"><a href="#cb17-286" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(cool_trans_lm_small<span class="sc">$</span>residuals)</span>
<span id="cb17-287"><a href="#cb17-287" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cool_trans_lm_small)</span>
<span id="cb17-288"><a href="#cb17-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-289"><a href="#cb17-289" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Compact =</span> .<span class="dv">75</span>, <span class="at">WallA =</span> <span class="dv">345</span>, <span class="at">twoStories =</span> <span class="dv">1</span>, <span class="at">GlazingA =</span> <span class="fl">0.1</span>)</span>
<span id="cb17-290"><a href="#cb17-290" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>twoStories <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dat<span class="sc">$</span>twoStories)</span>
<span id="cb17-291"><a href="#cb17-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-292"><a href="#cb17-292" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(cool_trans_lm_small, <span class="at">newdata =</span> dat, <span class="at">interval =</span> <span class="st">'confidence'</span>, <span class="at">level =</span> .<span class="dv">9</span>)</span>
<span id="cb17-293"><a href="#cb17-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-294"><a href="#cb17-294" aria-hidden="true" tabindex="-1"></a><span class="do">######</span></span>
<span id="cb17-295"><a href="#cb17-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-296"><a href="#cb17-296" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_trans_lm)</span>
<span id="cb17-297"><a href="#cb17-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-298"><a href="#cb17-298" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cool_trans_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-299"><a href="#cb17-299" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(cool_trans_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-300"><a href="#cb17-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-301"><a href="#cb17-301" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heat_trans_lm)</span>
<span id="cb17-302"><a href="#cb17-302" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_trans_lm)</span>
<span id="cb17-303"><a href="#cb17-303" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(heat_trans_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-304"><a href="#cb17-304" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(heat_trans_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-305"><a href="#cb17-305" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(heat_trans_lm<span class="sc">$</span>residuals)</span>
<span id="cb17-306"><a href="#cb17-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-307"><a href="#cb17-307" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heat)<span class="sc">+</span></span>
<span id="cb17-308"><a href="#cb17-308" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(Compact), <span class="at">y =</span> <span class="fu">log</span>(Heat), <span class="at">color =</span> twoStories))<span class="sc">+</span></span>
<span id="cb17-309"><a href="#cb17-309" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(Compact),</span>
<span id="cb17-310"><a href="#cb17-310" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="fu">predict</span>(heat_trans_lm), </span>
<span id="cb17-311"><a href="#cb17-311" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> twoStories))</span>
<span id="cb17-312"><a href="#cb17-312" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heat)<span class="sc">+</span></span>
<span id="cb17-313"><a href="#cb17-313" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">/</span>(WallA<span class="sc">**</span><span class="dv">2</span>), <span class="at">y =</span> <span class="fu">log</span>(Heat), <span class="at">color =</span> twoStories))<span class="sc">+</span></span>
<span id="cb17-314"><a href="#cb17-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">/</span>(WallA<span class="sc">**</span><span class="dv">2</span>),</span>
<span id="cb17-315"><a href="#cb17-315" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="fu">predict</span>(heat_trans_lm), </span>
<span id="cb17-316"><a href="#cb17-316" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> twoStories))</span>
<span id="cb17-317"><a href="#cb17-317" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heat)<span class="sc">+</span></span>
<span id="cb17-318"><a href="#cb17-318" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> GlazingA, <span class="at">y =</span> <span class="fu">log</span>(Heat), <span class="at">color =</span> twoStories))<span class="sc">+</span></span>
<span id="cb17-319"><a href="#cb17-319" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> GlazingA,</span>
<span id="cb17-320"><a href="#cb17-320" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> <span class="fu">predict</span>(heat_trans_lm), </span>
<span id="cb17-321"><a href="#cb17-321" aria-hidden="true" tabindex="-1"></a>                          <span class="at">color =</span> twoStories))</span>
<span id="cb17-322"><a href="#cb17-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-323"><a href="#cb17-323" aria-hidden="true" tabindex="-1"></a>cool_reduced_log_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cool <span class="sc">~</span> <span class="fu">sqrt</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> <span class="fu">sqrt</span>(GlazingA) <span class="sc">+</span> twoStories<span class="sc">*</span>WallA, <span class="at">data =</span> energy)</span>
<span id="cb17-324"><a href="#cb17-324" aria-hidden="true" tabindex="-1"></a>cool_reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(Cool) <span class="sc">~</span> <span class="fu">sqrt</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> <span class="fu">sqrt</span>(GlazingA), <span class="at">data =</span> energy)</span>
<span id="cb17-325"><a href="#cb17-325" aria-hidden="true" tabindex="-1"></a>heat_reduced_log_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(Heat) <span class="sc">~</span> Compact <span class="sc">+</span> <span class="fu">sqrt</span>(WallA) <span class="sc">+</span> twoStories <span class="sc">+</span> <span class="fu">sqrt</span>(GlazingA), <span class="at">data =</span> energy)</span>
<span id="cb17-326"><a href="#cb17-326" aria-hidden="true" tabindex="-1"></a>heat<span class="sc">$</span>residuals <span class="ot">&lt;-</span> heat_reduced_log_model<span class="sc">$</span>residuals</span>
<span id="cb17-327"><a href="#cb17-327" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(energy)</span>
<span id="cb17-328"><a href="#cb17-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-329"><a href="#cb17-329" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heat) <span class="sc">+</span></span>
<span id="cb17-330"><a href="#cb17-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Compact, <span class="at">y =</span> residuals)) <span class="sc">+</span></span>
<span id="cb17-331"><a href="#cb17-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-332"><a href="#cb17-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-333"><a href="#cb17-333" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heat) <span class="sc">+</span></span>
<span id="cb17-334"><a href="#cb17-334" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">sqrt</span>(WallA), <span class="at">y =</span> residuals)) <span class="sc">+</span></span>
<span id="cb17-335"><a href="#cb17-335" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-336"><a href="#cb17-336" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heat) <span class="sc">+</span></span>
<span id="cb17-337"><a href="#cb17-337" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">sqrt</span>(GlazingA), <span class="at">y =</span> residuals)) <span class="sc">+</span></span>
<span id="cb17-338"><a href="#cb17-338" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span>
<span id="cb17-339"><a href="#cb17-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-340"><a href="#cb17-340" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_reduced_log_model)</span>
<span id="cb17-341"><a href="#cb17-341" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(heat_reduced_log_model, <span class="at">which =</span> <span class="dv">4</span>)</span>
<span id="cb17-342"><a href="#cb17-342" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_reduced)</span>
<span id="cb17-343"><a href="#cb17-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-344"><a href="#cb17-344" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_reduced_log_model)</span>
<span id="cb17-345"><a href="#cb17-345" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(cool_reduced_log_model, <span class="at">which =</span> <span class="dv">4</span>)</span>
<span id="cb17-346"><a href="#cb17-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-347"><a href="#cb17-347" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(heat_reduced_log_model<span class="sc">$</span>residuals)</span>
<span id="cb17-348"><a href="#cb17-348" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(heat_reduced_log_model<span class="sc">$</span>residuals)</span>
<span id="cb17-349"><a href="#cb17-349" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(heat_reduced_log_model<span class="sc">$</span>residuals)</span>
<span id="cb17-350"><a href="#cb17-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-351"><a href="#cb17-351" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(cool_reduced_log_model<span class="sc">$</span>residuals)</span>
<span id="cb17-352"><a href="#cb17-352" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cool_reduced_log_model<span class="sc">$</span>residuals)</span>
<span id="cb17-353"><a href="#cb17-353" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(cool_reduced_log_model<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>