---
title: "Building design and energy efficiency"
authors: "Andrew Pochman, Spencer Wilson, Walter Vogelmann, Zach Perry"
output: pdf_document
---

<style type="text/css">
h1.title {
font-size: 40px;
text-align: center;
}
h4.author {
font-size: 40px;
text-align: center;
}
</style>

\newpage

```{r setup, include=FALSE}
# load all necessary packages here
```

# Abstract

Here, you will briefly summarize the entire report, including the data used, questions of interest, and relevant findings.

# 1 Problem and Motivation

In this section, you will describe the background information about the study that is necessary to understand why the data are important.  In other words, why was it important to gather the data in the first place?

## 1.1 Data Description

```{text}
Briefly state the source of your data and describe the relevant variables that **you will use** in your project.  Include important details such as units for the different variables, and what the ``observational units" (rows in the data set) represent (e.g., individuals, countries, etc.)
```

This data was originally sampled from architectural simulation software (Ecotect) that simulates many things about architectural designs, including their energy efficiency and heating/cooling requirements. Each observation represents a different design for a building and its simulated heating and cooling load. Below is a table describing the different variables collected:

| Feature |	 Range |	Unit |	Description |
|-:|-:|-:|-:|
| RelativeCompactness | 0.68–0.98 |	- |	The volume to surface ratio compared to the most compact shape with same volume |
| SurfaceArea |	514–808 |	m2 |	The total area occupied by the floor plan of the building |
| WallArea |	245–416 |	m2 |	Total area of the exterior building wall including all openings |
| RoofArea |	110–220 |	m2 |	the surface area of the roof |
| OverallHeight |	3.5–7 |	m |	Height from the lowest point of conditioned space to the highest point |
| Orientation |	2–5 |	- |	Direction the building faces |
| GlazingArea |	0–0.4 |	m2 |	The total area of the walls occupied by windows |
| Output |
| HeatingLoad  | 6–43 |	KWh/m2 |	Amount of heat added per square meter to maintain comfortable temperature |
| CoolingLoad |	10–48 |	KWh/m2 |	The amount of heat removed per square meter to maintain comfortable temperature |

## 1.2 Questions of Interest

```{text}
Briefly and clearly state the two main questions that you will investigate throughout the report.  These questions should be stated in scientific, and not statistical language.  For example, "Is the slope of log of per capita GDP significantly different from zero?" should instead by give as "Does the log of per capita GDP have an effect on the average life expectancy of females in a given country?"
```

Do architectural factors such as the dimensions of the walls and roof, the size of windows, and overall compactness of a house have an effect on the energy efficiency of keeping it cool?

Do these same factors have a different effect on the efficiency of warming the house?

## 1.3 Regression Methods

For each question of interest listed in Section 2, describe what regression models, techniques, and tools you will use to fully answer it.  These should include any plots you will use for exploratory analysis or diagnostic checks, as well as methods of inference you will use. 

# 2 Analyses, Results, and Interpretation

Conduct the analysis in a logical fashion, including necessary code (and not any superfluous code) and its output.  Give simple interpretations of your findings related to the questions of interest.

# 3 Conclusions

Give additional context to you results and interpretations from Section 5 with respect to the data set and its purpose.  Describe any potential weaknesses in your analysis, and how they may affect the reliability of the results.

# 4 Contributions

For each member of the group, write a short paragraph describing their contribution to this project and the report.  It is up to you to decide how to divide up the work, so long as everyone is contributing approximately equally. 

## APPENDIX

If there are any analyses, such as exploratory plots/summaries or work you did to determine appropriate transformations, or any relevant material that does not belong in one of the sections above, these can go in the Appendix.  If you don't have any material like this, you can remove this section.


